print('basic program structure')
print('add login feature')
print('change website font')
print('add haya picture')
print('add form section')
print('add news section')
print('update news section')
print('add footer section')
print('change the font to Montesserat')
print('update the header navigation list')
print('change website logo')
print('adding training department')
print('adding development department')
print('meeting schedual')
print('boss greeting')
