print('basic program structure')
print('add login feature')
print('change website font')
print('change hero picture')
print('add form section')
print('add news section')
print('update news section')
print('add footer section')
print('change the font to Montesserat')
print('update the header navigation list')
